-- ============================================================
-- DSMNRU SIH 2026 Portal - Seed Data
-- SAMPLE/DEMO DATA - Replace with official content before launch
-- ============================================================

-- Event Settings
INSERT INTO event_settings (key, value, description) VALUES
  ('max_team_size', '6', 'Maximum number of members per team'),
  ('min_team_size', '3', 'Minimum number of members required to select a problem'),
  ('max_teams_per_problem', '3', 'Maximum teams that can select the same problem'),
  ('allow_problem_change', 'true', 'Allow teams to change their selected problem'),
  ('require_approval', 'false', 'Require faculty approval for problem selection'),
  ('selection_locked', 'false', 'Lock all problem selections'),
  ('registration_open', 'true', 'Allow new team registrations'),
  ('event_dates', '{"registration_end": "2026-09-15", "problem_selection_end": "2026-09-20", "internal_event_date": "2026-09-27"}', 'Important event dates')
ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- PROBLEM STATEMENTS (20 realistic SIH 2026-style problems)
-- ============================================================

INSERT INTO problems (ps_id, title, category, theme, ministry, organization, background, description, expected_solution, constraints, keywords, max_teams, current_team_count) VALUES

('SIH26-1001', 'AI-Powered Assistive Communication Device for Persons with Speech and Motor Disabilities',
 'Software', 'Accessibility & Inclusion',
 'Ministry of Social Justice and Empowerment',
 'Department of Empowerment of Persons with Disabilities',
 'Millions of persons with speech and motor disabilities in India lack access to affordable, context-aware communication tools. Existing AAC (Augmentative and Alternative Communication) devices are expensive and not localized for Indian languages.',
 'Develop an AI-powered communication assistant that enables individuals with speech and motor disabilities to communicate effectively using gaze tracking, gesture recognition, or brain-computer interface (BCI) inputs. The system should support multiple Indian regional languages including Hindi, and be deployable on low-cost hardware.',
 'A cross-platform (mobile/desktop) application featuring: gaze/gesture-based input, NLP-powered predictive text in Hindi and regional languages, offline operation, text-to-speech synthesis, and exportable communication logs. Cost should be below ₹5000 for hardware implementation.',
 'Must support at least 3 Indian languages. Must function offline. Response time under 200ms.',
 ARRAY['accessibility', 'disability', 'AI', 'NLP', 'assistive technology', 'speech', 'gaze tracking'],
 3, 1),

('SIH26-1002', 'Smart Grievance Redressal System for University Students Using Natural Language Processing',
 'Software', 'Smart Education',
 'Ministry of Education',
 'University Grants Commission (UGC)',
 'University students often face difficulties in raising and tracking grievances related to academics, administration, and hostel issues. Existing systems are manual, slow, and lack transparency.',
 'Build an NLP-powered grievance redressal platform for university students that can automatically categorize, prioritize, and route complaints to appropriate departments. Include sentiment analysis, multilingual support, and real-time status tracking with automated escalation workflows.',
 'A web/mobile portal with: NLP-based complaint categorization, priority scoring, automatic routing, real-time tracking dashboard, multilingual interface (Hindi + English), and WhatsApp/SMS notification integration. Admin panel for grievance management and analytics.',
 'Must handle concurrent submissions. Must support Hindi input. Response SLA tracking required.',
 ARRAY['NLP', 'education', 'grievance', 'universities', 'sentiment analysis', 'automation'],
 3, 2),

('SIH26-1003', 'Blockchain-Based Tamper-Proof Academic Certificate Verification System',
 'Software', 'Blockchain & Cybersecurity',
 'Ministry of Education',
 'National Academic Depository (NAD)',
 'Fake academic certificates are a growing problem in India, causing losses to employers and universities. Physical verification is slow and expensive.',
 'Develop a blockchain-based system for issuing, storing, and verifying academic certificates and marksheets. Universities can issue digital credentials that employers or institutions can verify instantly without intermediaries. The system should integrate with DigiLocker.',
 'A permissioned blockchain network (Hyperledger Fabric or Ethereum) with: university onboarding portal, credential issuance API, QR-code-based instant verification, DigiLocker integration, mobile app for students, and employer verification portal.',
 'Must comply with IT Act 2000. Must integrate with DigiLocker API. Zero fake positive verification rate.',
 ARRAY['blockchain', 'certificates', 'education', 'verification', 'DigiLocker', 'Hyperledger'],
 3, 0),

('SIH26-1004', 'Real-Time Traffic Management System for Smart Cities Using Computer Vision and IoT',
 'Software', 'Smart Automation',
 'Ministry of Housing and Urban Affairs',
 'Smart Cities Mission',
 'Indian cities face severe traffic congestion causing pollution, delays, and accidents. Existing signal systems are fixed-timer based and cannot adapt to real-time conditions.',
 'Design and implement an adaptive traffic signal control system using computer vision and IoT sensors. The system should detect vehicle density at intersections, dynamically adjust signal timing, prioritize emergency vehicles, and integrate with city command centers.',
 'An edge-AI solution with: CCTV-based vehicle counting using YOLO models, IoT sensor integration, dynamic signal timing algorithm, emergency vehicle detection, central dashboard for traffic operators, and predictive traffic forecasting using historical data.',
 'Must work in varying lighting conditions. False positive rate < 2%. Latency < 500ms for signal switching.',
 ARRAY['computer vision', 'IoT', 'traffic', 'smart city', 'YOLO', 'edge AI', 'autonomous'],
 3, 1),

('SIH26-1005', 'AI-Based Crop Disease Detection and Advisory System for Farmers Using Smartphone Cameras',
 'Software', 'Agriculture, FoodTech & Rural Development',
 'Ministry of Agriculture and Farmers Welfare',
 'Indian Council of Agricultural Research (ICAR)',
 'Indian farmers lose 20-30% of crop yield annually due to undetected diseases. Access to agronomists in rural areas is limited and expensive.',
 'Develop a smartphone app that allows farmers to photograph crops and receive instant AI-powered disease diagnosis with treatment recommendations in local languages. The system should work offline in low-connectivity areas and maintain a disease database updated by ICAR.',
 'Mobile app with: CNN-based disease detection (accuracy >90%), offline model inference, regional language support (10+ languages), treatment advisory with local agri-input store locator, farmer community forum, and weather-integrated advisory dashboard.',
 'Must work offline. Must support 15+ crop types. Must provide diagnosis in < 3 seconds.',
 ARRAY['agriculture', 'AI', 'crop disease', 'farmers', 'CNN', 'offline', 'smartphone'],
 3, 0),

('SIH26-1006', 'Digital Platform for Rehabilitation Progress Tracking of Persons with Physical Disabilities',
 'Software', 'Accessibility & Inclusion',
 'Ministry of Social Justice and Empowerment',
 'Rehabilitation Council of India',
 'Rehabilitation of persons with physical disabilities is a long process requiring consistent monitoring. There is no centralized system to track progress, therapist assignments, and treatment outcomes across rehabilitation centers.',
 'Build a comprehensive rehabilitation management platform that enables therapists, doctors, and family members to track patient progress, set milestones, record exercises, and generate outcome reports. Include gamification elements to motivate patients during therapy.',
 'A multi-role web/mobile platform with: patient progress tracking, exercise library with video instructions, gamification (achievements, streaks), therapist assignment management, family update notifications, outcome analytics, and HIPAA-compliant data storage.',
 'Must be WCAG 2.1 AA compliant. Must support offline data entry. Must integrate with existing hospital systems.',
 ARRAY['rehabilitation', 'disability', 'healthcare', 'gamification', 'progress tracking', 'therapy'],
 3, 2),

('SIH26-1007', 'Predictive Analytics System for Water Quality Monitoring in Rural Areas',
 'Software', 'Smart Resource Conservation',
 'Ministry of Jal Shakti',
 'National Water Mission',
 'Many rural areas in India face water contamination issues. Existing monitoring is infrequent and reactive. Villages lack real-time data on water quality parameters.',
 'Develop an IoT-integrated water quality monitoring system that collects real-time data from sensors (pH, TDS, turbidity, bacteria) and uses ML models to predict contamination events. Send early warnings to village panchayats and district authorities.',
 'IoT dashboard with: multi-parameter sensor integration, ML-based contamination prediction, SMS/WhatsApp alert system for panchayats, GIS mapping of water sources, historical trend analysis, and a citizen reporting mobile app.',
 'Must handle sensor dropouts gracefully. Must work in 2G connectivity areas. Alert latency < 5 minutes.',
 ARRAY['water quality', 'IoT', 'rural', 'ML', 'GIS', 'predictive analytics', 'Jal Shakti'],
 3, 0),

('SIH26-1008', 'Automated Sign Language Interpretation System for Deaf-Mute Community',
 'Software', 'Accessibility & Inclusion',
 'Ministry of Social Justice and Empowerment',
 'Ali Yavar Jung National Institute for Deaf (AYJNID)',
 'The deaf-mute community faces communication barriers in hospitals, courts, government offices, and educational institutions due to shortage of sign language interpreters.',
 'Create a real-time AI system that interprets Indian Sign Language (ISL) gestures using computer vision and converts them to text and speech. Also provide text/speech to ISL animation conversion for two-way communication.',
 'A real-time interpretation system: CNN+LSTM gesture recognition, ISL database covering 5000+ signs, text-to-ISL 3D avatar animation, integration with video conferencing platforms (Zoom, Teams), mobile app, and browser extension.',
 'ISL recognition accuracy > 85%. Real-time (< 300ms latency). Must cover medical and legal vocabulary.',
 ARRAY['sign language', 'ISL', 'accessibility', 'deaf', 'computer vision', 'LSTM', 'real-time'],
 3, 1),

('SIH26-1009', 'Cybersecurity Threat Intelligence Platform for Critical Infrastructure Protection',
 'Software', 'Blockchain & Cybersecurity',
 'Ministry of Electronics and Information Technology',
 'National Critical Information Infrastructure Protection Centre (NCIIPC)',
 'India''s critical infrastructure (power grids, financial systems, hospitals) faces increasing cyber threats. There is no unified threat intelligence platform for sharing attack patterns across sectors.',
 'Build a threat intelligence sharing and analysis platform where critical infrastructure operators can report and receive real-time threat indicators (IOCs). Integrate ML-based threat correlation, MITRE ATT&CK framework mapping, and automated incident response playbooks.',
 'A STIX/TAXII-compatible threat intelligence platform with: IOC ingestion and sharing, ML-based threat correlation, ATT&CK technique mapping, automated alerting, incident response playbooks, API for SIEM integration, and anonymized public threat feed.',
 'Must comply with CERT-In guidelines. Data must be encrypted at rest and in transit. High availability (99.9%).',
 ARRAY['cybersecurity', 'threat intelligence', 'IOC', 'MITRE ATT&CK', 'critical infrastructure', 'CERT-In'],
 3, 0),

('SIH26-1010', 'Smart Elderly Care Monitoring System Using AI and Wearable IoT Sensors',
 'Software', 'MedTech / BioTech / HealthTech',
 'Ministry of Health and Family Welfare',
 'National Health Mission',
 'India''s elderly population is growing rapidly. Many elderly individuals live alone or in care homes without adequate monitoring. Falls, cardiac events, and missed medication are major concerns.',
 'Develop a comprehensive elderly care monitoring system using wearable IoT devices and AI. Detect falls, monitor vital signs, track medication adherence, and enable one-touch emergency calling. Provide family and caregiver dashboards with health trend analytics.',
 'Wearable device integration (heart rate, SpO2, fall detection, GPS) with: real-time health dashboard, emergency SOS with GPS location sharing, medication reminder system, AI anomaly detection, caregiver mobile app, and telemedicine integration.',
 'Wearable battery life > 48 hours. SOS alert latency < 10 seconds. Must work with existing smartwatches.',
 ARRAY['elderly care', 'IoT', 'wearable', 'health monitoring', 'AI', 'fall detection', 'telemedicine'],
 3, 1),

('SIH26-1011', 'Decentralized Land Records Management System Using Blockchain for Fraud Prevention',
 'Software', 'Blockchain & Cybersecurity',
 'Ministry of Rural Development',
 'Department of Land Resources',
 'Land record fraud and disputes are prevalent in India. Multiple registries maintain inconsistent records and there is no single source of truth for land ownership.',
 'Implement a blockchain-based land records system that ensures immutable, transparent, and tamper-proof property records. Enable digital mutation, encumbrance certificate generation, and ownership transfer workflows.',
 'A permissioned blockchain system with: immutable ownership records, digital mutation workflow, encumbrance certificate API, integration with state registration departments, citizen portal for record viewing, and court-admissible digital evidence generation.',
 'Must integrate with existing state revenue department APIs. Must support Aadhaar-based authentication. Audit trail for all changes.',
 ARRAY['blockchain', 'land records', 'fraud prevention', 'Aadhaar', 'rural development', 'immutable'],
 3, 0),

('SIH26-1012', 'AI-Powered Mental Health Screening and Support Platform for Students',
 'Software', 'MedTech / BioTech / HealthTech',
 'Ministry of Education',
 'National Institute of Mental Health and Neurosciences (NIMHANS)',
 'Mental health issues among students are increasing post-pandemic. Screening, access to counselors, and stigma remain major barriers to seeking help.',
 'Build an AI-powered mental health platform for educational institutions that conducts periodic screenings, provides self-help resources, connects students with counselors, and enables anonymous peer support. Detect at-risk students and trigger counselor outreach.',
 'A student mental health platform with: PHQ-9/GAD-7 based digital screening, AI risk stratification, anonymous peer support forum, therapist booking system, mindfulness exercises, crisis intervention workflow, and institutional analytics dashboard for counseling centers.',
 'Must be completely anonymous for students. HIPAA/DPDP compliant. Crisis intervention < 2 hours.',
 ARRAY['mental health', 'students', 'AI', 'screening', 'counseling', 'NIMHANS', 'DPDP'],
 3, 2),

('SIH26-1013', 'Automated Road Pothole Detection and Reporting System Using Vehicle Sensors and AI',
 'Software', 'Transportation & Logistics',
 'Ministry of Road Transport and Highways',
 'National Highways Authority of India (NHAI)',
 'Potholes cause thousands of accidents and vehicle damage annually in India. Road survey teams take weeks to identify and report potholes, leading to delayed repairs.',
 'Create a crowdsourced pothole detection system using smartphone accelerometers and GPS that automatically identifies potholes, geolocates them, and submits repair requests to the appropriate authority. Include an authority dashboard for work order management.',
 'Mobile app with: accelerometer-based pothole detection (accuracy >90%), automatic GPS geotagging, photo submission, authority routing by road jurisdiction, work order management system, repair status tracking, and community validation mechanism.',
 'Must work without camera permission if needed. Battery drain < 5% per hour. False positive rate < 5%.',
 ARRAY['roads', 'pothole', 'crowdsourcing', 'accelerometer', 'GPS', 'NHAI', 'transportation'],
 3, 0),

('SIH26-1014', 'Digital Waste Management System with AI-Based Segregation and Tracking',
 'Hardware', 'Clean & Green Technology',
 'Ministry of Environment, Forest and Climate Change',
 'Central Pollution Control Board',
 'India generates 62 million tonnes of waste annually with less than 20% recycling rate. Poor segregation at source and lack of tracking from generation to disposal are major challenges.',
 'Design an intelligent waste management system with smart bins equipped with AI cameras for automatic waste segregation, weight sensors, and fill-level monitoring. Integrate with waste collection vehicles for optimized routing and a citizen reporting app.',
 'Smart bin hardware with: AI camera (plastic/organic/hazardous classification), fill-level sensor, weight measurement, IoT connectivity. Software: vehicle route optimization, citizen app, municipality dashboard, recycling analytics, and carbon credit calculation.',
 'Hardware must be IP65 rated. Segregation accuracy > 85%. Solar-powered operation preferred.',
 ARRAY['waste management', 'IoT', 'AI', 'segregation', 'smart bin', 'recycling', 'environment'],
 3, 1),

('SIH26-1015', 'Real-Time Flood Early Warning and Evacuation Management System',
 'Software', 'Disaster Management',
 'Ministry of Jal Shakti',
 'National Disaster Management Authority (NDMA)',
 'Floods cause massive loss of life and property in India annually. Early warning systems exist but are not integrated with evacuation planning and community notification.',
 'Build an integrated flood early warning and evacuation management platform that aggregates data from river gauges, rainfall sensors, satellite imagery, and weather APIs to predict flood events. Automatically trigger evacuation notifications and manage shelter logistics.',
 'An integrated platform with: multi-source data aggregation, ML flood prediction model, automated community SMS/call alerts in regional languages, digital evacuation route maps, shelter capacity management, rescue coordination dashboard, and post-flood damage assessment module.',
 'Warning lead time minimum 12 hours. Alert delivery success > 95%. Must work in network-degraded conditions.',
 ARRAY['flood', 'disaster management', 'early warning', 'evacuation', 'NDMA', 'ML', 'regional languages'],
 3, 0),

('SIH26-1016', 'Smart Solar Panel Fault Detection and Performance Optimization System',
 'Hardware', 'Renewable / Sustainable Energy',
 'Ministry of New and Renewable Energy',
 'Solar Energy Corporation of India (SECI)',
 'India aims for 500 GW renewable energy by 2030. Solar panel faults go undetected for weeks, causing significant energy losses. Current monitoring lacks predictive maintenance capability.',
 'Develop a hardware-software system for real-time solar panel health monitoring. Use thermal imaging cameras, IV curve tracers, and ML models to detect faults (hot spots, delamination, bypass diode failure) and predict maintenance needs.',
 'Hardware module with thermal camera and IV tracer + software: automated fault classification, performance degradation alerts, maintenance scheduling, energy loss quantification, panel-level performance dashboard, and ROI calculation for maintenance interventions.',
 'Must withstand outdoor conditions (-20°C to 60°C). Fault detection accuracy > 90%. Compatible with existing monitoring inverters.',
 ARRAY['solar energy', 'fault detection', 'thermal imaging', 'IoT', 'predictive maintenance', 'SECI', 'renewable'],
 3, 1),

('SIH26-1017', 'AI-Driven Job Matching Platform for Persons with Disabilities',
 'Software', 'Accessibility & Inclusion',
 'Ministry of Social Justice and Empowerment',
 'Department of Empowerment of Persons with Disabilities',
 'Persons with disabilities (PwD) face significant barriers in finding suitable employment. Generic job portals do not account for accessibility needs, reasonable accommodation requirements, or disability-friendly employers.',
 'Create a specialized job matching platform for PwD that uses AI to match candidates with disability-friendly employers based on skills, accommodation needs, and workplace facilities. Include resume building with accessibility, interview preparation, and employer rating system.',
 'An accessible job portal (WCAG 2.2 AAA) with: AI skill-disability-job matching, employer certification for disability-friendliness, accommodation requirement matching, screen-reader-optimized UI, video interview practice with sign language support, and government job reservation tracking.',
 'Fully WCAG 2.2 AAA compliant. Must support 21 types of disabilities under RPwD Act 2016. UDID card integration.',
 ARRAY['disability', 'employment', 'AI matching', 'accessibility', 'RPwD', 'UDID', 'PwD'],
 3, 0),

('SIH26-1018', 'Drone-Based Medical Supply Delivery System for Remote and Tribal Areas',
 'Hardware', 'MedTech / BioTech / HealthTech',
 'Ministry of Health and Family Welfare',
 'National Health Mission',
 'Remote and tribal areas in India lack timely access to medicines, vaccines, and blood products. Road access is often disrupted during monsoons or natural disasters.',
 'Design a drone delivery system for medical supplies to remote health centers and village-level health workers. Include automated dispatch, real-time tracking, temperature monitoring for cold-chain items, and emergency blood delivery capability.',
 'DGCA-compliant delivery drone with: 30+ km range, cold-chain cargo compartment, autonomous navigation, real-time tracking, emergency parachute deployment, ground station management software, and integration with PHC inventory systems.',
 'DGCA BVLOS compliance required. Cold chain maintaining 2-8°C for vaccines. Payload minimum 2 kg.',
 ARRAY['drone', 'medical delivery', 'remote areas', 'tribal', 'cold chain', 'DGCA', 'healthcare'],
 3, 2),

('SIH26-1019', 'Smart Braille and Tactile Learning System for Visually Impaired Students',
 'Hardware', 'Accessibility & Inclusion',
 'Ministry of Social Justice and Empowerment',
 'National Association for the Blind',
 'Visually impaired students lack access to quality educational materials in Braille. Converting textbooks to Braille is slow, expensive, and not scalable.',
 'Develop a low-cost smart learning device that converts digital textbook content to Braille on demand using refreshable Braille cells. Include text-to-speech, audio descriptions for diagrams, interactive math learning, and teacher management software.',
 'Hardware: Refreshable Braille display (40 cells), tactile graphics module, audio output, wireless connectivity. Software: PDF/textbook parsing, math equation rendering in Braille (Nemeth code), teacher content management, and progress tracking.',
 'Cost < ₹15,000 per device. Battery life > 8 hours. Compatible with NCERT digital textbooks.',
 ARRAY['Braille', 'visually impaired', 'education', 'hardware', 'accessibility', 'tactile', 'refreshable Braille'],
 3, 0),

('SIH26-1020', 'Unified Digital Platform for Rehabilitation Services and Disability Certificate Management',
 'Software', 'Accessibility & Inclusion',
 'Ministry of Social Justice and Empowerment',
 'Rehabilitation Council of India',
 'Persons with disabilities face difficulties navigating multiple government portals for disability certificates, benefits, and rehabilitation services. Each scheme has separate portals with no interoperability.',
 'Build a unified digital platform that serves as a one-stop portal for all disability-related services: UDID application, disability certificate tracking, scheme enrollment, rehabilitation center finder, assistive device application, and grievance redressal.',
 'A unified portal integrated with: Aadhaar, UDID database, state disability welfare departments, scheme eligibility engine, rehabilitation center directory with bed availability, assistive device procurement portal, and WhatsApp-based status updates.',
 'Must integrate with 15+ government APIs. DigiLocker integration mandatory. Must be available in 22 scheduled languages.',
 ARRAY['disability', 'UDID', 'rehabilitation', 'government services', 'Aadhaar', 'unified platform', 'digital India'],
 3, 1)

ON CONFLICT (ps_id) DO NOTHING;
